/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PensaoAlimenticiaRouteImport } from './routes/pensao-alimenticia'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ImobiliarioRouteImport } from './routes/imobiliario'
import { Route as ConsumidorRouteImport } from './routes/consumidor'
import { Route as IndexRouteImport } from './routes/index'

const PensaoAlimenticiaRoute = PensaoAlimenticiaRouteImport.update({
  id: '/pensao-alimenticia',
  path: '/pensao-alimenticia',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ImobiliarioRoute = ImobiliarioRouteImport.update({
  id: '/imobiliario',
  path: '/imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorRoute = ConsumidorRouteImport.update({
  id: '/consumidor',
  path: '/consumidor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consumidor': typeof ConsumidorRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/pensao-alimenticia': typeof PensaoAlimenticiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consumidor': typeof ConsumidorRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/pensao-alimenticia': typeof PensaoAlimenticiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consumidor': typeof ConsumidorRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/pensao-alimenticia': typeof PensaoAlimenticiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consumidor'
    | '/imobiliario'
    | '/inventario'
    | '/pensao-alimenticia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consumidor'
    | '/imobiliario'
    | '/inventario'
    | '/pensao-alimenticia'
  id:
    | '__root__'
    | '/'
    | '/consumidor'
    | '/imobiliario'
    | '/inventario'
    | '/pensao-alimenticia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsumidorRoute: typeof ConsumidorRoute
  ImobiliarioRoute: typeof ImobiliarioRoute
  InventarioRoute: typeof InventarioRoute
  PensaoAlimenticiaRoute: typeof PensaoAlimenticiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pensao-alimenticia': {
      id: '/pensao-alimenticia'
      path: '/pensao-alimenticia'
      fullPath: '/pensao-alimenticia'
      preLoaderRoute: typeof PensaoAlimenticiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imobiliario': {
      id: '/imobiliario'
      path: '/imobiliario'
      fullPath: '/imobiliario'
      preLoaderRoute: typeof ImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor': {
      id: '/consumidor'
      path: '/consumidor'
      fullPath: '/consumidor'
      preLoaderRoute: typeof ConsumidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsumidorRoute: ConsumidorRoute,
  ImobiliarioRoute: ImobiliarioRoute,
  InventarioRoute: InventarioRoute,
  PensaoAlimenticiaRoute: PensaoAlimenticiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
